
var mp3Durations = [315	, 223	,
273	,
211	,
143	,
243	,
241	,
202	,
209	,
342	,
220	,
225	,
245	,
223	,
247	,
346	,
280	,
193	,
199	,
246	,
279	,
268	,
259	,
247	,
225	,
265	,
254	,
196	,
162	,
356	,
249	,
253	,
230	,
264	,
357	,
186	,
166	,
272	,
428	,
535	,
171	,
185	,
292	,
265	,
240	,
225	,
312	,
172	,
161	,
360	,
234	,
166	,
486	,
463	,
531	,
467	,
202	,
249	,
250	,
323	,
226	,
461	,
206	,
166	,
257	,
479	,
545	,
506	,
376	,
210	,
306	,
243	,
206	,
262	,
175	,
217	,
306	,
328	,
297	,
212	,
483	,
242	,
269	,
144	,
334	,
298	,
180	,
294	,
258	,
220	,
358	,
219	,
217	,
249	,
489	,
454	,
415	,
335	,
200	,
268	,
274	,
267	,
256	,
314	,
187	,
236	,
199	,
505	,
244	,
212	,
187	,
212	,
242	,
214	,
265	,
217	,
486	,
450	,
492	,
476	,
488	,
346	,
204	,
220	,
171	,
239	,
222	,
250	,
159	,
294	,
257	,
152	,
159	,
308	,
205	,
244	,
226	,
197	,
220	,
232	,
367	,
415	,
278	,
494	,
249	,
343	,
324	,
315	,
253	,
250	,
284	,
268	,
230	,
273	,
255	,
182];

var state3names = [
"Adrian Lux - Damaged (Original Mix).mp3",
"AHA - Take On Me.mp3",
"Alejandro.mp3",
"Amy Winehouse - Rehab.mp3",
"Aretha Franklin - Respect.mp3",
"ATTLAS - Ryat.mp3",
"Bee Gees - Stayin' Alive.mp3",
"Billy Idol - Dancing With Myself.mp3",
"Billy Idol - White Wedding Pt 1.mp3",
"Billy Joel - Piano Man.mp3",
"Blondie - Heart Of Glass.mp3",
"Bon Jovi - It's My Life.mp3",
"Bon Jovi - Livin' On A Prayer.mp3",
"Bon Jovi - Shot Through The Heart.mp3",
"Bon Jovi - Wanted Dead Or Alive.mp3",
"Bonnie Tyler - I Need a Hero.mp3",
"Boston - More than A Feeling.mp3",
"Carly Rae Jepsen - Call Me Maybe.mp3",
"Cascada - Every Time We Touch.mp3",
"C+C Music Factory - Gonna Make You Sweat (Everybody Dance Now) ft. Freedom Williams.mp3",
"Cupid Shuffle.mp3",
"Cutting Crew - I Just Died In Your Arms Tonight.mp3",
"Cyndi Lauper - Girls Just Want To Have Fun.mp3",
"Daft Punk - Get Lucky.mp3",
"Daft Punk - Harder, Better, Faster, Stronger.mp3",
"Daryl Hall _ John Oates - Maneater.mp3",
"David Bowie - Starman.mp3",
"Dead Or Alive - You Spin Me Round.mp3",
"Devo - Whip It.mp3",
"download (1).mp3",
"download.mp3",
"Ed Sheeran - Shape of You.mp3",
"Ellie Goulding - Burn.mp3",
"Eminem ft. Rihanna - Love the Way You Lie (song + lyrics).mp3.mp3",
"Enzo Bennet - Colours.mp3",
"Eric Prydz - Breathe ft. Rob Swire.mp3",
"Eric Prydz - Call On Me.mp3",
"Eric Prydz - Every Day (Andy C Remix).mp3",
"Eric Prydz - Generate.mp3",
"Eric Prydz - Opus.mp3",
"Eric Prydz - Pjanoo.mp3",
"Eric Prydz VS CHVRCHES - Tether.mp3",
"Eurythmics - Sweet Dreams (Are Made of This).mp3",
"Foreigner - Jukebox Hero (2).mp3",
"Franz Ferdinand - Take Me Out.mp3",
"Greensky Bluegrass - Just Listening.mp3",
"Groove Is In The Heart - Deee-lite 1990.mp3",
"I Am X-Ray - Pretty Rave Girl.mp3",
"Icona Pop - I Love It (feat. Charli XCX).mp3",
"Iron Maiden - 2 Minutes to Midnight.mp3",
"Iron Maiden - Run to The Hills.mp3",
"JAMES BROWN - I Got You [ I FEEL GOOD ].mp3",
"Jeremy Olander - Atlanten (Original Mix).mp3",
"Jeremy Olander - Groover (Original Mix) [microCastle].mp3",
"Jeremy Olander - Panorama (Original Mix) [Suara].mp3",
"Jeremy Olander - Talespin (Original Mix) [Suara].mp3",
"Journey_Jounry - Anyway You Want It.mp3",
"Journey_Journy - Don't Stop Believin.mp3",
"Journey - Small Town Girl.mp3",
"Kanses - Carry On My Wayward Son.mp3",
"Katy Perry - Firework.mp3",
"Kazusa _ Shingo Nakamura - Dice.mp3",
"Ke$ha - TiK ToK.mp3",
"Kill Paris - Float.mp3",
"Kool _ The Gang - Celebration.mp3",
"Kyohei Akagawa - Abendrot (Original Mix).mp3",
"Kyohei Akagawa - Airo (Original Mix).mp3",
"Kyohei Akagawa - As No World Idealized (KIWAMU Remix).mp3",
"Kyohei Akagawa - Vor Dem Fliegen (Kobana Remix).mp3",
"Lady Gaga - Applause.mp3",
"Lady Gaga - Bad Romance.mp3",
"Lady Gaga - Just Dance.mp3",
"La Roux - Bulletproof.mp3",
"LMFAO - Party Rock Anthem.mp3",
"LMFAO - Sexy and I Know It.mp3",
"Lou bega - Mambo number 5.mp3",
"MACKLEMORE X RYAN LEWIS - AND WE DANCED.mp3",
"Madonna - 01. Like A Prayer.mp3",
"Madonna - Express Yourself.mp3",
"Major Lazer - Pon De Floor.mp3",
"Mango - Kites (Shingo Nakamura Remix) HD1080P.mp3",
"Marcia Griffiths - Electric Boogie (The Electric Slide).mp3",
"Mark Ronson - Uptown Funk ft. Bruno Mars.mp3",
"MARVIN GAYE _ TAMMI TERRELL - -Ain't no Mountain High Enough-.mp3",
"Masanori Yasuda - Ajisai (Shingo Nakamura Remix).mp3",
"Mazde - Battas (feat. LissA).mp3",
"Melvv - Glide.mp3",
"Michael Jackson - michael jackson - micheal jackson - billie jean.mp3.mp3",
"Michael Jackson_Micheal Jackson - Beat It.mp3",
"Michael Jackson- Rock With You.mp3",
"Michael Jackson - Thriller.mp3",
"Miley Cyrus _ Mumford _ Sons - Little Wrecking Ball.mp3.mp3",
"Naked Eyes - Always Something There To Remind Me.mp3",
"Naughty By Nature - O.P.P..mp3",
"Nhato - Etude (Kazusa Remix) (1).mp3",
"Nhato - Eureka (Original Mix).mp3",
"Nhato - Forbidden Souls.mp3",
"Nhato - Magic (Original Mix).mp3",
"Nicki Minaj - Super Bass.mp3",
"ODESZA - It's Only (feat. Zyra).mp3",
"Of Monsters and Men - King and Lionheart.mp3",
"Of Monsters and Men - Little Talks.mp3",
"OneRepublic - Counting Stars.mp3.mp3",
"Pat Benatar - Hit Me With Your Best Shot.mp3",
"Paul Stanley - Live to Win.mp3",
"Pharrell Williams - Happy.mp3",
"P!nk - Get The Party Started.mp3",
"Pryda - Loving You (Original Mix).mp3",
"Quarterflash - Harden My Heart.mp3",
"Queen - Don't Stop Me Now.mp3",
"Radioactive-Imagine Dragons.mp3.mp3",
"Rick Astley - Never Gonna Give You Up (3).mp3",
"Rihanna - S_M.mp3",
"Rihanna - We Found Love.mp3",
"Salt-N-Pepa - Push It.mp3",
"Shakira - Hips Don't Lie.mp3",
"Shingo Nakamura - Blue Light (Original Mix).mp3",
"Shingo Nakamura - Fauna (Original Mix).mp3",
"Shingo Nakamura _ Kazusa - Move On (EcueD Remix).mp3",
"Shingo Nakamura - Linear Light (Original Mix).mp3",
"Shingo Nakamura - Memory Of The Sea (Original Mix).mp3",
"Shingo Nakamura - Small Image (Original Mix).mp3",
"Slightly Left of Centre - Love The Way You Move (LTWYM) Official Music Video.mp3",
"SNAP! - The Power.mp3",
"Spice Girls - Wannabe.mp3",
"Stan Bush - Dare.mp3",
"super freak rick james.mp3",
"Survivor - Eye Of The Tiger.mp3",
"Tainted Love Soft Cell.mp3",
"Technotronic - Pump Up The Jam.mp3",
"The B-52's - Love Shack.mp3",
"The Beatles - Twist And Shout.mp3",
"The Contours Do You Love Me.mp3",
"The Final Countdown - Europe.mp3",
"The Human League - Don't You Want Me.mp3",
"The Killers - Human.mp3",
"The Killers - Mr. Brightside.mp3",
"The Killers - Somebody Told Me.mp3",
"The Killers - When You Were Young.mp3",
"The Touch - Stan Bush (HD Restoration).mp3",
"Tin5ha - Clear Blue Sky (Original Mix) [Otographic Music].mp3",
"Tin5ha - Remember the Sunset (Original Mix) [OTO014] [HD 1080p].mp3",
"Tycho - Awake.mp3",
"Tycho - Dive.mp3",
"Tycho - Horizon.mp3",
"Tycho - Hours.mp3",
"Tycho - Montana.mp3",
"Tycho - See.mp3",
"U Can't Touch This - MC Hammer.mp3",
"Usher Ft. Lil' Jon & Ludacris - Yeah.mp3",
"Village People - Y.M.C.A..mp3",
"Wagakki Band - Senbonzakura.mp3",
"Wham! - Wake Me Up Before You Go-Go (Sub. Español - English lyrics).mp3",
"What is Love.mp3",
"Wild Cherry - Play That Funky Music White Boy.mp3",
"Yello - Oh Yeah.mp3"];

var state2names = ["state2end.mp3", "state2start.mp3"];

module.exports.mp3Durations = mp3Durations;
module.exports.state3names = state3names;
module.exports.state2names = state2names;
